/**
 * Generates src/index.ts (the icon component barrel) and src/registry.ts
 * (the metadata registry) from src/icons/*.tsx + src/icons/*.json.
 *
 * Unlike a barrel generator that has to *guess* the exported component name
 * from file contents (regex-matching `export function Foo(`), every icon
 * here is named identically to its file — Bell.tsx exports `Bell` — so the
 * component name is derived from the filename directly. No guessing, no
 * naming-inconsistency report needed.
 *
 * What this *does* still validate, and fails the build on:
 *   - every .tsx must have a matching .json metadata file and vice versa
 *   - every .json must satisfy icon.schema.json's required fields
 *   - every icon name must be PascalCase (matches Lucide's own convention,
 *     and is what makes "component name === file name" safe to assume)
 *   - every .tsx must start with a `"use client"` directive — the icons use
 *     `motion/react` internally, so a missing directive would silently break
 *     any consumer importing this package into a React Server Component
 */

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const iconsDir = join(root, "src", "icons");

const REQUIRED_JSON_FIELDS = ["contributors", "tags", "categories"];
const PASCAL_CASE_RE = /^[A-Z][A-Za-z0-9]*$/;

const errors = [];

function fail(message) {
  console.error(`[generate-exports] ${message}`);
  process.exit(1);
}

const files = readdirSync(iconsDir);
const tsxNames = new Set(
  files
    .filter((f) => f.endsWith(".tsx"))
    .map((f) => f.replace(/\.tsx$/, ""))
);
const jsonNames = new Set(
  files.filter((f) => f.endsWith(".json")).map((f) => f.replace(/\.json$/, ""))
);

const missingJson = [...tsxNames].filter((n) => !jsonNames.has(n)).sort();
const orphanJson = [...jsonNames].filter((n) => !tsxNames.has(n)).sort();

if (missingJson.length > 0) {
  fail(
    `${missingJson.length} icon(s) have a .tsx but no matching .json metadata file:\n` +
      missingJson.map((n) => `  - ${n}.tsx`).join("\n")
  );
}
if (orphanJson.length > 0) {
  fail(
    `${orphanJson.length} .json metadata file(s) have no matching .tsx icon (stale entry?):\n` +
      orphanJson.map((n) => `  - ${n}.json`).join("\n")
  );
}

const names = [...tsxNames].sort((a, b) => a.localeCompare(b));

for (const name of names) {
  if (!PASCAL_CASE_RE.test(name)) {
    errors.push(`${name}.tsx: icon name is not PascalCase`);
    continue;
  }

  const meta = JSON.parse(readFileSync(join(iconsDir, `${name}.json`), "utf-8"));
  const missingFields = REQUIRED_JSON_FIELDS.filter((f) => !(f in meta));
  if (missingFields.length > 0) {
    errors.push(`${name}.json: missing required field(s): ${missingFields.join(", ")}`);
  }

  const source = readFileSync(join(iconsDir, `${name}.tsx`), "utf-8");
  if (!/^"use client";/.test(source)) {
    errors.push(
      `${name}.tsx: missing a leading \`"use client";\` directive — required since ` +
        `every icon uses motion/react internally`
    );
  }
}

if (errors.length > 0) {
  fail(`${errors.length} icon validation error(s):\n` + errors.map((e) => `  - ${e}`).join("\n"));
}

const indexContent =
  `// AUTO-GENERATED by \`npm run generate:exports\` (scripts/generate-exports.mjs).\n` +
  `// Do not edit by hand. Source of truth: src/icons/<Name>.tsx + src/icons/<Name>.json\n\n` +
  names.map((n) => `export { ${n} } from "./icons/${n}";`).join("\n") +
  `\nexport type { MoticonIconProps } from "./icons/types";\n`;

writeFileSync(join(root, "src", "index.ts"), indexContent);
console.log(`[generate-exports] ${names.length} icons -> src/index.ts`);
